# Sample workflow for building and deploying a website to GitHub Pages
name: Deploy C4 to Azure Static Web

on:
  schedule:
   - cron:   0,30 8-18 * * 1-5
  # Runs on pushes targeting the default branch and c4 files
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_call:    
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow only one concurrent deployment, skipping runs queued between the run in progress and the latest queued.
# However, do NOT cancel in-progress runs, as we want to allow these production deployments to be completed.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build-c4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive 
      - name: Update submodules to latest
        run: git submodule update --init --remote --recursive

      - name: Build
        uses: likec4/actions@v1
        with:
          action: build --base "./"
          output: dist
          # required if you don't set a custom domain for the repository
          # https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites
          base: ${{ steps.pages.outputs.base_path }}
          # (optional) by default, the bundled version is used, which is faster due to skipping the installation
          likec4-version: latest
        
      - name: Deploy to Azure Static Website
        uses: Azure/static-web-apps-deploy@v1
        with:
             azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_MOSS_00CF8A403 }}
             repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
             action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
             app_location: "/dist/" # App source code path
             api_location: "" # Api source code path - optional
             output_location: "./dist" # Built app content directory - optional
             skip_app_build: false
          ###### End of Repository/Build Configurations ######



